# DATABASE (environment)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# LIQUIBASE
spring.liquibase.change-log=classpath:db.changelog/db.changelog-demo.yaml

# MAIL
mail.enabled=false

# Docker
spring.docker.compose.enabled=false

# Logs
logging.level.org.springframework.jdbc=DEBUG

# Ports
server.port=8082

